# Generated by Django 5.2.10 on 2026-02-25 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_telegram_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Обычный пользователь'), ('manager', 'Менеджер'), ('courier', 'Курьер')], default='customer', max_length=20, verbose_name='Роль'),
        ),
    ]
